import { BiomeType, LocationType, type MapNode } from './WorldTypes';
import { FactionType } from '../Factions/FactionTypes';

export const INITIAL_MAP_NODES: Record<string, MapNode> = {
    'lawrence': {
        id: 'lawrence',
        name: 'Lawrence',
        description: 'The Free State stronghold. A center of anti-slavery activity and frequent target of border ruffians.',
        biome: BiomeType.Settlement,
        type: LocationType.Town,
        coordinates: { x: 60, y: 50 },
        connections: ['lecompton', 'topeka', 'franklin'],
        resources: ['Timber', 'Information', 'Supplies'],
        factionControl: FactionType.FreeState,
        dangerLevel: 7,
        hasShop: true,
    },
    'lecompton': {
        id: 'lecompton',
        name: 'Lecompton',
        description: 'The pro-slavery capital. Home of the "Bogus Legislature" and a dangerous place for abolitionists.',
        biome: BiomeType.Settlement,
        type: LocationType.Town,
        coordinates: { x: 55, y: 52 }, // 12 miles from Lawrence
        connections: ['lawrence', 'tecumseh'],
        resources: ['Supplies', 'Bounties'],
        factionControl: FactionType.ProSlavery,
        dangerLevel: 8,
        hasShop: true,
    },
    'topeka': {
        id: 'topeka',
        name: 'Topeka',
        description: 'Seat of the rival Free State government. A key stop on the Underground Railroad.',
        biome: BiomeType.Settlement,
        type: LocationType.Town,
        coordinates: { x: 40, y: 50 },
        connections: ['lawrence', 'manhattan'],
        resources: ['Supplies', 'Politics'],
        factionControl: FactionType.FreeState,
        dangerLevel: 5,
        hasShop: true,
    },
    'osawatomie': {
        id: 'osawatomie',
        name: 'Osawatomie',
        description: 'A center of radical abolitionism, associated with John Brown.',
        biome: BiomeType.Settlement,
        type: LocationType.Town,
        coordinates: { x: 65, y: 70 },
        connections: ['pottawatomie_creek', 'paola'],
        resources: ['Supplies', 'Recruits'],
        factionControl: FactionType.Abolitionist,
        dangerLevel: 9,
        hasShop: true,
    },
    'pottawatomie_creek': {
        id: 'pottawatomie_creek',
        name: 'Pottawatomie Creek',
        description: 'A rural settlement area with scattered cabins. Tension is high here.',
        biome: BiomeType.Forest,
        type: LocationType.NaturalLandmark,
        coordinates: { x: 62, y: 75 },
        connections: ['osawatomie'],
        resources: ['Timber', 'Water'],
        dangerLevel: 6,
    },
    'uniontown': {
        id: 'uniontown',
        name: 'Uniontown',
        description: 'A trading post on the Potawatomi reservation. A hub for commerce.',
        biome: BiomeType.Settlement,
        type: LocationType.TradingPost,
        coordinates: { x: 30, y: 40 },
        connections: ['topeka'],
        resources: ['Furs', 'Trade Goods'],
        dangerLevel: 3,
        hasShop: true,
    },
    'franklin': {
        id: 'franklin',
        name: 'Franklin',
        description: 'A pro-slavery stronghold just south of Lawrence. A constant threat.',
        biome: BiomeType.Settlement,
        type: LocationType.Town,
        coordinates: { x: 60, y: 55 },
        connections: ['lawrence'],
        resources: ['Supplies', 'Weapons'],
        factionControl: FactionType.ProSlavery,
        dangerLevel: 8,
    },
    'tecumseh': {
        id: 'tecumseh',
        name: 'Tecumseh',
        description: 'A pro-slavery town near Lecompton.',
        biome: BiomeType.Settlement,
        type: LocationType.Town,
        coordinates: { x: 48, y: 51 },
        connections: ['lecompton', 'topeka'],
        resources: ['Supplies'],
        factionControl: FactionType.ProSlavery,
        dangerLevel: 6,
    },
    'manhattan': {
        id: 'manhattan',
        name: 'Manhattan',
        description: 'A Free State settlement at the junction of the Kansas and Big Blue rivers.',
        biome: BiomeType.Settlement,
        type: LocationType.Town,
        coordinates: { x: 20, y: 45 },
        connections: ['topeka'],
        resources: ['Timber', 'Water', 'Supplies'],
        factionControl: FactionType.FreeState,
        dangerLevel: 4,
    },
    'paola': {
        id: 'paola',
        name: 'Paola',
        description: 'A settlement near the Missouri border.',
        biome: BiomeType.Settlement,
        type: LocationType.Town,
        coordinates: { x: 70, y: 70 },
        connections: ['osawatomie'],
        resources: ['Supplies'],
        factionControl: FactionType.ProSlavery,
        dangerLevel: 7,
    },
};
